FROM node20.11.1-alpine3.18 as base

FROM base as builder

WORKDIR /app

COPY . .

RUN npm i -g pnpm --registry=https://registry.npmmirror.com
RUN pnpm i --registry https://registry.npmmirror.com

# RUN npx prisma generate

FROM base as runner

WORKDIR /app

COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

ENV NEXT_TELEMETRY_DISABLED 1

# COPY prisma ./prisma
COPY startup.sh ./startup.sh
RUN chmod +x /app/startup.sh

EXPOSE 3000

ENTRYPOINT ["sh", "/app/startup.sh"]