import Image from 'next/image'

// import type { ComponentPropsWithoutRef } from 'react'
// NOTE: generated by https://maketext.io/ https://www.diyiziti.com/
import logo from '@/assets/yangtze.svg'

// eslint-disable-next-line unused-imports/no-unused-vars
// props: ComponentPropsWithoutRef<typeof Image>
export function Logo() {
  return (
    <Image
      src={logo}
      alt="logo"
      className="w-24"
      unoptimized
      // NOTE: https://nextjs.org/docs/pages/api-reference/components/image#priority
      priority
      // {...props}
    />
  )
}
