import Image from 'next/image'
import type { ComponentPropsWithoutRef } from 'react'

// NOTE: generated by https://maketext.io/ https://www.diyiziti.com/
import logo from '@/assets/yangtze.svg'

// eslint-disable-next-line unused-imports/no-unused-vars
export function Logo(props: ComponentPropsWithoutRef<'svg'>) {
  // -mt-32 tailwind.config.ts extend margin
  return (
    <Image
      src={logo}
      alt=""
      className="h-14"
      unoptimized
      // NOTE: https://nextjs.org/docs/pages/api-reference/components/image#priority
      priority
    />
  )
}
