#!/bin/sh
# Disable concurent to run `check-types` after ESLint in lint-staged
cd "$(dirname "$0")/.." && npx lint-staged --concurrent false

# ./node_modules/.bin/ls-lint

./node_modules/.bin/sort-package-json
